hashicorp/vault-rails

lib/vault/encrypted_model.rb
This fixes an issue where the encoded value would be saved on the instance variable, but that was not the actual value that would be returned on a reload.
=> Set the decoded value in the instance variable

lib/vault/encrypted_model.rb, spec/integration/rails_spec.rb, spec/unit/encrypted_model_spec.rb
This fixes a bug where, in tests, if you called `resource.reload`, the old values for encrypted columns would still be persisted.
/cc @pearkes
=> Allow reloading

lib/vault/encrypted_model.rb, spec/integration/rails_spec.rb, spec/unit/encrypted_model_spec.rb
This leverage's ActiveRecord's dirty attribute tracking to allow users to query before/after values when saving a model.
=> Track dirty attributes

lib/vault/encrypted_model.rb, spec/dummy/app/models/person.rb, spec/dummy/lib/binary_serializer.rb, spec/integration/rails_spec.rb
Prior to this commit, each interaction with a vault_attribute would issue a _new_ HTTP request to Vault and cache the result. This caused race conditions and unexpected behaviors. Additionally, it was a very poor optimization that turned out to actually be less performant that eager loading all the values from Vault at once.
This commit changes vault-rails to decrypt all values from Vault after the object is loaded, and then encrypt the values using Vault only right before the object is to be saved.
Closes https://github.com/hashicorp/vault-rails/pull/21
/cc @handlers @pearkes
=> Load and persist Vault attribute at init and save

lib/vault/rails.rb
This PR makes it so the second line of the warning message prints.
=> Fix with_retries so the second line of the warning prints

.travis.yml, vault.gemspec
* Split commands into array to make it clearer what is failing when something fails.
* ~~Updates vault version~~ Runs against various Vault versions.  I don't know if you actually want this (and I'm guessing not pulling from the public DL was intentional as well) but the link that was there was 404 so I just made the easiest change.
* Pin `mime-types` gem if using Ruby 1.x, not sure if this is the best way to do it but it seems to work.
=> Update Travis build

lib/vault/encrypted_model.rb, spec/dummy/app/models/lazy_person.rb, spec/integration/rails_spec.rb
This partially restores the old behavior of only decrypting
encrypted values on use. Rather than doing them one at a time though
(which would reintroduce a consistency problem), all encrypted
attributes are decrypted as soon as any encrypted attributes are
accessed.
=> Add ability to lazy decrypt attributes

.travis.yml
The webserver for https://releases.hashicorp.com now only supports TLS version 1.2 and above. The Travis CI build environment needs to use Trusty as the distribution in order to use OpenSSL libraries which support this version of TLS.
See: https://github.com/travis-ci/travis-ci/issues/7131
=> CI: Support TLS v1.2

gemfiles/rails_4.0.gemfile.lock, gemfiles/rails_4.1.gemfile.lock, gemfiles/rails_4.2.gemfile.lock
💁  The lockfiles for the test matrix of gems has fallen out of step with the Gemfiles, causing build failures. These updates bring them back in step with the source files.
=> CI: Update lockfiles used for test matrix

lib/vault/rails.rb, lib/vault/rails/configurable.rb, spec/unit/rails/configurable_spec.rb
💁  When a Rails application that uses `Vault::Rails` runs its test suite using an in-memory cipher (a common use case), this can result in many hundreds of log messages warning about using an insecure cipher in a production-like environment. This increases the logging noise and reduces the value of logging during testing. 😿 
These changes add configuration methods to disable these in-memory warnings improves the signal to noise ratio when using this gem in a test environment.
Closes #43
=> Configurable warning messages for in-memory ciphers

.travis.yml
Updating the 0.6 version that's tested against from 0.6.0 to 0.6.5, and added in the latest 0.7, 0.8 and 0.9 releases as well.
=> Update tested Vault versions.

.travis.yml
Given MRI 2.2 is no longer supported, maybe it's worth removing this to keep the build matrix a little more manageable?
=> Update CI Ruby versions, add 2.5 to the mix.

README.md
Hi. 
I've just added the comma in README because without it I have an error
```
syntax error, unexpected ':', expecting keyword_end
serialize: :json
```
=> add comma before serialize in README

README.md, lib/vault/encrypted_model.rb, lib/vault/rails.rb, spec/dummy/app/models/lazy_person.rb, spec/dummy/app/models/person.rb, spec/dummy/db/migrate/20150428220101_create_people.rb, spec/dummy/db/schema.rb, spec/integration/rails_spec.rb, spec/unit/encrypted_model_spec.rb
This adds support for passing a context to Vault Transit encrypt/decrypt operations, allowing an application to specify a context per record or a `belongs_to` relation (such as a user, team, or organization). The context can be a string, or if given a proc or symbol, will generate the context for each encrypt/decrypt request.
This changes the signature of `Vault::Rails.encrypt` and `Vault::Rails.decrypt`. Each had an arity of 3-4, and they now have an arity of 3 and 2 optional keyword arguments. The minor version number should be bumped on release (since the major version is still 0).
=> Add support for key derivation with a context

lib/vault/rails.rb, spec/unit/vault/rails_spec.rb
The Ruby OpenSSL AES 128 cipher requires a 16-byte key. The previous implementation of #memory_key_for generated a base64 string and then truncated it to 16 bytes. This could cause longer paths/keys (and now contexts) to have the same memory key for different values.
This change uses an MD5 digest to generate a mostly-unique key for different key/path/context inputs.
=> Use a digest to generate a memory key

README.md
The `vault_lazy_decrypt!` method was added a couple years back but never documented, so the functionality is only discoverable by looking at the code.
I _may_ have gotten too heavy-handed with the example, so lemme know if I should pare it down 😂
=> Add documentation for the vault_lazy_decrypt configuration option

README.md, lib/vault/encrypted_model.rb, spec/dummy/app/models/lazy_person.rb, spec/dummy/app/models/person.rb, spec/dummy/db/migrate/20150428220101_create_people.rb, spec/dummy/db/schema.rb, spec/integration/rails_spec.rb
This adds a `:default` option to `vault_attribute`, allowing a default value to be set if the underlying value is `nil`.
```rb
vault_attribute :metadata,
serializer: :json,
default: {}
vault_attribute :access_level,
default: "readonly"
```
This enables a simple fix for applications affected by the breaking change introduced in #81 for `serialize: :json` empty values.
=> Add default option to vault_attribute

README.md
Table name is `people` not `persons`.
=> FIX: Small typo in migration inside README.

Appraisals, lib/vault/encrypted_model.rb, spec/unit/encrypted_model_spec.rb
This is built on top of #66, but I'm just going to focus here on what's been done in 169f021adb0dcfe4e83954505de2854644610513 (and further commits after that, should there be changes):
* Instead of manually crafting dirty state support, I'm opting to use Rails' own approaches for this, which arguably makes the behaviour more reliable and consistent - even though there's now some allowances of slightly different behaviour across versions.
* The catch is that these helpers don't exist in Rails 4.1. Maybe this is a good opportunity to end 4.1 support?
* I've left in references to model instance variables (e.g. `@ssn`), given they're covered by specs - though I personally would prefer to scrap that support, which makes the code a little more simpler. They're ideally not part of any public …
=> Rails 5.2 support

.travis.yml, Appraisals, lib/vault/encrypted_model.rb, vault.gemspec
This is a pretty simple change to support changes made in Rails 6.0, most notably removing the `previous_changes_include?` method.
This also goes through and removes sqlite3 being locked at 1.3.x
=> Adding Rails 6.0+ support

README.md, lib/vault/rails.rb, lib/vault/rails/configurable.rb, lib/vault/rails/errors.rb, spec/integration/rails_spec.rb, spec/unit/rails/configurable_spec.rb
Store ciphertext with a prefix in dev mode, similar to real vault.
I have an app with validations and I check that the ciphertext starts with `vault:`, but I can't have this check on in development mode unfortunately. With this change, I can simplify my validation and always have it on.
Please let me know if you want any changes. Thanks!
=> Store ciphertext with a prefix in dev mode

lib/vault/encrypted_model.rb, lib/vault/rails.rb, lib/vault/rails/configurable.rb, spec/dummy/app/models/person.rb, spec/dummy/db/migrate/20150428220101_create_people.rb, spec/dummy/db/schema.rb, spec/integration/rails_spec.rb, spec/spec_helper.rb, vault.gemspec
The vault ruby gem was updated to allow usage of the transform secrets engine a little while back. This PR allows for the usage of that engine within rails, extending the `vault_attribute` class function to accept a `transform_secret` hash that allows for the usage of FPE with a vault-internal tweak_source. Support for additional tweak_sources and transformation types may be provided in the future.
Similar to the Transit engine already implemented, this functionality uses a db column either provided by the user with the `encrypted_column` option, or uses the `vault_attribute` name provided with a `_encrypted` appended as a suffix (e.g. `vault_attribute :ssn` will have `ssn_encrypted` as the column that stores the value.
Note: due to constraints from ActiveRecord, we do NOT encourage …
=> Add Transform Secrets engine support

.circleci/config.yml, spec/integration/rails_spec.rb, vault.gemspec
These changes:
* Drop support for Rails 4.2, _which really already happened with the 0.6.0 release_ (see below)
* Remove forceful usage of Bundler 1.x in CI (which was only required because of Rails 4.x)
---
In #67, Rails 5+ support was added in the form of ditching our own dirty attribute logic and instead utilizing the fancy new Attributes API, which was officially introduced in Rails 5 but present (sorta) in Rails 4.2 as well. This very obviously cut off support of vault-rails for Rails 4.1, which doesn't have this API at all. Tests passed for Rails 4.2, so it looked good.
However, the Attributes API in Rails 4.2 is actually totally private API - it's no more than a refactoring in anticipation of the real API in 5, and some of the API was accidentally exposed in documentation anyway in …
=> Drop Rails 4.2 support

lib/vault/encrypted_model.rb, spec/integration/rails_spec.rb
Fixes a regression caused by https://github.com/hashicorp/vault-rails/pull/99/commits/6c5b1a3c2a6e1f9e7e7f228dee9ce6e1717ce548
The usage of instance_variable_get means that if an attribute is assigned to `nil`, the variable to signal that attributes are loaded is `false` - meaning that any intentional setting of `nil` results in attributes getting reloaded on the next read and wiping that `nil` value back to whatever it was before. I've added some specs to describe this behavior.
=> Fix dirty nil assignments

lib/vault/encrypted_model.rb
There's a stray `require "pry"` on current master that causes issues outside of the development and test environments - pry is a development dependency, so unless `pry` is loaded by the calling application in production, this `require` produces a `LoadError`:
<details>
<summary>Expand for full stack trace</summary>
```
rake aborted!
LoadError: cannot load such file -- pry
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:292:in `require'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:292:in `block in require'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:258:in `load_dependency'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.1.7/lib/active_support/dependencies. …
```
=> remove stray "require pry"

lib/vault/encrypted_model.rb, spec/integration/rails_spec.rb
After destroying a record, ActiveRecord marks the in-memory object as frozen and unable to be altered. This was fine in older versions of Rails prior to the attributes API, and it's mostly fine now. However, if lazy decrypt is enabled and you need to access an encrypted attribute after the destroy happens -- for instance, as part of a `dependent: :destroy` chain -- vault-rails attempts to set the plaintext attribute on the frozen object, raising a "Can't modify frozen hash" error.
As a workaround, this PR ensures that attributes are decrypted before a destroy so the plain text values can be accessed by after-destroy hooks if needed.
Currently, I've set this as universal behavior, since being able to access encrypted attributes after a destroy was the default prior to …
=> allow lazy decrypted vault attributes to be referenced after a destroy

spec/dummy/config/environments/development.rb, spec/dummy/config/environments/test.rb, spec/integration/rails_spec.rb
Removes the remaining deprecation warnings that make their way in to CI output in all supported versions of Rails.
=> Remove remaining Rails 5.0 thru 6.0 deprecations

vault.gemspec
This gem utilizes ActiveSupport, specifically, and doesn't need to have a hard dependency on the 'rails' metagem itself.
This is a topical change at the moment with https://github.com/rails/rails/issues/41750; if an application does not use ActiveStorage and ActionMailbox, it may choose specifically include the Rails components it needs instead of `rails` itself to avoid installing the mimemagic gem. Even if you aren't actually using the mimemagic functionality, transient dependencies - like this gem - must also not require it.
As this gem doesn't require anything other than ActiveSupport, we'll loosen constraints this gem imposes.
=> Loosen dependency to only ActiveSupport

.circleci/config.yml
Fun story! CI [suddenly started failing](https://app.circleci.com/pipelines/github/hashicorp/vault-rails/134/workflows/c6a0fcb4-6e9a-450b-9e02-2688df12b5dc/jobs/2810) due to an SSL error when downloading the Vault binary from releases.hashicorp.com:
https://github.com/hashicorp/vault-rails/blob/8c953255b7d8f18c95e284e49e2596df5f9efe10/.circleci/config.yml#L33
Upon further investigation, this proved to be due to [an outdated SSL library](https://www.zoocha.com/news/fixing-issues-multiple-servers-caused-recently-expired-root-certificate).
It _also_ turns out that Circle is going to be deprecating the (super old) Ubuntu 16.04 image we were using on May 31, 2022, which is in, uh, 6 days. So let's kill two birds with one stone and update Ubuntu.
=> resolve issues with CI

CHANGELOG.md, lib/vault/rails.rb, lib/vault/rails/version.rb, vault.gemspec
The vault-ruby gem [now has the ability](https://github.com/hashicorp/vault-ruby/pull/266) to retry on 412 errors (caused by a mismatch between the WAL index on a standby node and the token; see [Server-Side Consistent Tokens FAQ](https://www.vaultproject.io/docs/faq/ssct)).
This PR updates the minimum required version of the vault gem and ensures that the vault-rails gem's version of the `with_retries` method passes the new error type (`Vault::MissingRequiredStateError`) as something to automatically retry on.
=> Use vault-ruby 0.17.0 to add automatic retry on 412 errors

spec/support/vault_server.rb
same as https://github.com/hashicorp/vault-ruby/pull/294
The main change here is to not read the ~/.vault-token file for the token, just hard-code it.
this takes out the race condition that was happening and allows us to have more consistent CI runs
=> CI refactor

CHANGELOG.md, lib/vault/rails/version.rb, vault.gemspec
Updating `vault` dependency to support TLS v1.3 (https://github.com/hashicorp/vault-ruby/pull/297).
=> TF-8697: Update `vault` dependency

README.md
The key [by default uses the attribute name](https://github.com/hashicorp/vault-rails/blob/main/lib/vault/encrypted_model.rb#L184) and not the column name. So this just updates the README to avoid confusion.
=> Updating README to clarify that keys use attribute by default
